import { expect, test } from '@playwright/test'

test('crea un futbolista y resuelve su primer evento', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /Comenzar mi historia/ }).click()
  await page.getByLabel('Nombre').fill('Lina')
  await page.getByLabel('Apellido').fill('Rojas')
  await page.getByRole('button', { name: /Construir mi origen/ }).click()
  await expect(page.getByText(/Antes del estadio estaba/)).toBeVisible()
  await page.getByRole('button', { name: /Empezar la carrera/ }).click()
  await expect(page.locator('.decision-scene')).toBeVisible()
  await expect(page.getByText('ETAPA ACTUAL')).toBeVisible()
  await expect(page.getByText('Fútbol base', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: /Descubrir acontecimiento|Cerrar el año/ })).toHaveCount(0)

  const eventTitle = await page.locator('.decision-scene h2').innerText()
  const choiceLabels = await page.locator('.decision-choice > strong').allInnerTexts()
  expect(choiceLabels.length).toBeGreaterThan(1)
  for (const choiceLabel of choiceLabels) {
    expect(choiceLabel).not.toContain(eventTitle)
    expect(choiceLabel.length).toBeLessThan(100)
  }

  await page.locator('.decision-choice').first().click()
  await expect(page.getByText('DECISIÓN TOMADA')).toBeVisible()
  await expect(page.getByText('LO QUE CAMBIÓ')).toBeVisible()
})

test('elige un club real y combina una rutina con un reto interactivo', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /Comenzar mi historia/ }).click()
  await page.getByLabel('Nombre').fill('Manu')
  await page.getByLabel('Apellido').fill('Vargas')
  await page.getByRole('radio', { name: /Gimnasia de Jujuy/ }).click()
  await page.getByRole('button', { name: /Construir mi origen/ }).click()
  await expect(page.getByText('Gimnasia y Esgrima de Jujuy')).toBeVisible()
  await page.getByRole('button', { name: /Empezar la carrera/ }).click()
  await expect(page.getByRole('img', { name: /Escudo de Gimnasia y Esgrima de Jujuy/ })).toBeVisible()
  await page.getByRole('button', { name: /Entrenador personal/ }).click()
  await expect(page.getByText('US$ 7K DISPONIBLES')).toBeVisible()
  await page.getByRole('button', { name: /Trabajo de velocidad/ }).click()
  await expect(page.getByText(/Sesión completada/)).toBeVisible()
  await page.getByRole('button', { name: /Duelo de penales/ }).click()
  await page.getByRole('button', { name: 'Arriba izquierda' }).click()
  await expect(page.locator('.penalty-flash')).toBeVisible()
  await page.getByRole('button', { name: 'Arriba centro' }).click()
  await page.getByRole('button', { name: 'Arriba derecha' }).click()
  await expect(page.getByText('TRABAJO COMPLETADO')).toBeVisible()
  await expect(page.getByText(/La mejora ya fue guardada/)).toBeVisible()
})

test('explica todos los sistemas y permite comprar en la tienda', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /Comenzar mi historia/ }).click()
  await page.getByLabel('Nombre').fill('Nora')
  await page.getByLabel('Apellido').fill('Suárez')
  await page.getByRole('button', { name: /Construir mi origen/ }).click()
  await page.getByRole('button', { name: /Empezar la carrera/ }).click()

  await page.getByRole('link', { name: 'Guía' }).click()
  await expect(page.getByRole('heading', { name: 'Media' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'El exterior' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Champions y copas' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'El semillero' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'El duelo' })).toBeVisible()

  await page.getByRole('link', { name: 'Tienda' }).click()
  await expect(page.locator('.shop-wallet strong')).toHaveText('US$ 12K')
  await expect(page.getByRole('heading', { name: 'Staff' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Lujo' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Legado' })).toBeVisible()
  await page.getByRole('button', { name: 'Comprar Reloj de rendimiento' }).click()
  await expect(page.getByRole('button', { name: 'Reloj de rendimiento adquirido' })).toBeDisabled()
  await expect(page.locator('.shop-wallet strong')).toHaveText('US$ 4K')

  await page.getByRole('link', { name: 'Ficha' }).click()
  await expect(page.getByText('MEDIA', { exact: true })).toBeVisible()
  await expect(page.getByText('FORMA', { exact: true })).toBeVisible()
  await expect(page.getByText('DINERO GANADO', { exact: true })).toBeVisible()
  await expect(page.getByText(/DUELO DE CARRERA/)).toBeVisible()
})

test('puede empezar su carrera en una de las cinco grandes ligas', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /Comenzar mi historia/ }).click()
  await page.getByLabel('Nombre').fill('Alex')
  await page.getByLabel('Apellido').fill('Martín')
  await page.getByRole('tab', { name: /España/ }).click()
  await page.getByRole('radio', { name: /Barcelona/ }).click()
  await page.getByRole('button', { name: /Construir mi origen/ }).click()
  await expect(page.getByText('FC Barcelona')).toBeVisible()
  await expect(page.getByText(/Barcelona · LALIGA/)).toBeVisible()
  await page.getByRole('button', { name: /Empezar la carrera/ }).click()
  await expect(page.getByRole('img', { name: /Escudo de FC Barcelona/ })).toBeVisible()
  await expect(page.locator('.hud-season small')).toHaveText('LALIGA')
})

test('puede empezar en Brasil con un escudo real', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /Comenzar mi historia/ }).click()
  await page.getByLabel('Nombre').fill('João')
  await page.getByLabel('Apellido').fill('Silva')
  await page.getByRole('tab', { name: /Brasil/ }).click()
  await page.getByRole('radio', { name: /Flamengo/ }).click()
  await page.getByRole('button', { name: /Construir mi origen/ }).click()
  await expect(page.getByText('Clube de Regatas do Flamengo')).toBeVisible()
  await expect(page.getByText(/Río de Janeiro · Brasileirão Série A/)).toBeVisible()
  await page.getByRole('button', { name: /Empezar la carrera/ }).click()
  await expect(page.getByRole('img', { name: /Escudo de Clube de Regatas do Flamengo/ })).toBeVisible()
  await expect(page.locator('.hud-season small')).toHaveText('Brasileirão Série A')
})

test('avanza solo al anuario tras dos acontecimientos y acelera la etapa juvenil', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /Comenzar mi historia/ }).click()
  await page.getByLabel('Nombre').fill('Mara')
  await page.getByLabel('Apellido').fill('Ledesma')
  await page.getByRole('button', { name: /Construir mi origen/ }).click()
  await page.getByRole('button', { name: /Empezar la carrera/ }).click()

  for (let decision = 0; decision < 2; decision += 1) {
    await expect(page.locator('.decision-scene')).toBeVisible()
    await page.locator('.decision-choice').first().click()
    await page.getByRole('button', { name: /Siguiente ahora/ }).click()
  }

  await expect(page.getByText('RESUMEN DE TEMPORADA')).toBeVisible()
  await expect(page.getByText('POSICIÓN FINAL', { exact: true })).toBeVisible()
  await expect(page.getByText('Todo lo que jugaste este año')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Liga Juvenil Regional' })).toBeVisible()
  await expect(page.locator('.standing-row')).toHaveCount(0)
  await expect(page.getByText(/Lo que dejó la temporada/)).toBeVisible()
  await page.getByRole('button', { name: /Comenzar la próxima temporada/ }).click()
  await expect.poll(() => page.evaluate(() => window.scrollY)).toBe(0)
  await expect(page.locator('.hud-season strong')).toHaveText('02')
  await expect(page.locator('.player-age strong')).toHaveText('12')
  await expect(page.locator('.hud-mission strong')).toContainText('0/2 decisiones')
  await expect(page.locator('.decision-scene')).toBeVisible()
})
